name: release
on:
  push:
    tags: ['v*.*.*']

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
      - run: git fetch --tags
      - name: check branch
        run: |
          br="$(git branch --contains $GITHUB_REF --format '%(refname:short)' main)"
          if [[ "$br" != "main" ]]; then
            echo "$br != main"
            exit 1
          fi
      - name: Build
        uses: ./.github/actions/build
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
      - name: release-notes
        run: 'echo "$(git tag -l --format="%(contents:body)" $GITHUB_REF_NAME)" > RELEASE_NOTES'
      - uses: softprops/action-gh-release@v2
        id: create_release
        with:
          body_path: RELEASE_NOTES
          fail_on_unmatched_files: true
          files: ./bin/ira-controller
          make_latest: true
          prerelease: false
